Script started on Tue 21 Nov 2017 07:04:14 PM PST
]0;yukih1@laguna:hw4[yukih1@laguna hw4]$ mkae[K[K[Kake
gcc -ansi -Wall -c -std=c99 FileIO.c -o FileIO.o
gcc -ansi -Wall -c -std=c99 DIPs.c -o DIPs.o
gcc -ansi -Wall -c -std=c99 Advanced.c -o Advanced.o
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a	
gcc -ansi -Wall -c -std=c99 PhotoLab.c -o PhotoLab.o
gcc -ansi -Wall -c Test.c -o Test.o
gcc -ansi -Wall -c -std=c99 Image.c -o Image.o
gcc -ansi -Wall -std=c99 FileIO.o PhotoLab.o Image.o Test.o -lfilter -L. -o PhotoLab
gcc -ansi -Wall -c -std=c99 PhotoLab.c -o PhotoLab_debug.o -DDEBUG -g
gcc -ansi -Wall -c Test.c -o Test_debug.o -DDEBUG -g
gcc  -std=c99 FileIO.o PhotoLab_debug.o Image.o Test_debug.o -lfilter -L. -o PhotoLabTest 
]0;yukih1@laguna:hw4[yukih1@laguna hw4]$ ./P
PhotoLab*     PhotoLabTest* 
]0;yukih1@laguna:hw4[yukih1@laguna hw4]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Motion Blur
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Constast of an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 19

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Motion Blur
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Constast of an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 20
You exit the program.
]0;yukih1@laguna:hw4[yukih1@laguna hw4]$ ./PhotoLab[22Gmake[Kexitmake clean[22Gscript[K[K[K[K[K[K[Kv[Ka[Kvalrm typescript[22Gvalgrind --leak-check=full ./PhotoLabTest[22Gll[Kvi PhotoLab.c[22Gll[Kvalgrind --leak-check=full ./PhotoLabTest
==100614== Memcheck, a memory error detector
==100614== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==100614== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==100614== Command: ./PhotoLabTest
==100614== 
Black and White tested!

Negative tested!

Color Filter tested!

Edge Detection tested!

Shuffle tested!

VFlip tested!

VMirror tested!

Add Border tested!

Add Noise tested!

Sharpen tested!

Posterize tested!

MotionBlur tested!

Crop tested!

Resize tested!

Brightness and Contrast tested!

Watermark tested!

==100614== 
==100614== HEAP SUMMARY:
==100614==     in use at exit: 0 bytes in 0 blocks
==100614==   total heap usage: 127 allocs, 127 frees, 16,683,939 bytes allocated
==100614== 
==100614== All heap blocks were freed -- no leaks are possible
==100614== 
==100614== For counts of detected and suppressed errors, rerun with: -v
==100614== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;yukih1@laguna:hw4[yukih1@laguna hw4]$ make clear[Kn
rm -rf *.o
rm -rf PhotoLab PhotoLabTest libfilter.a
rm -rf bw.ppm edge.ppm negative.ppm colorfilter.ppm shuffle.ppm vflip.ppm vmirror.ppm noise.ppm posterize.ppm border.ppm sharpen.ppm blur.ppm smallresize.ppm bigresize.ppm crop.ppm brightnessandcontrast.ppm watermark.ppm 
]0;yukih1@laguna:hw4[yukih1@laguna hw4]$ exit
exit

Script done on Tue 21 Nov 2017 07:08:54 PM PST
