Script started on Tue 24 Oct 2017 11:21:52 AM PDT
]0;yukih1@zuma:hw2[yukih1@zuma hw2]$ vi PhotoLab.c[20Gll[Kcd hw2EECS_22/hw2[20G~eecs22/bin/turnin.sh[20Gcd ..[K[20Ggcc PhotoLab.c -ansi -std=c99 -Wall -o PhotoLab[20G[37P./[30G[20Gls[K./PhotoLab[20G[37@gcc PhotoLab.c -ansi -std=c99 -Wall -o [67G
]0;yukih1@zuma:hw2[yukih1@zuma hw2]$ gcc PhotoLab.c -ansi -std=c99 -Wall -o PhotoLab[20Gvi PhotoLab.c[K[20Gll[Kcd hw2EECS_22/hw2[20G~eecs22/bin/turnin.sh[20Gcd ..[K[20G./PhotoLab[20Gls[K./PhotoLab
--------------------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG formet
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image 
 6: Sketch the edge of an image 
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Adder Border to an iamge
11: Test all functions
12: Exit
Please make your choice: 11
HSSOE.ppm was loaded successfully!
Black & White operation is done!
bw.ppm was saved successfully.
bw.jpg was stored for viewing.
Black and white tested!

HSSOE.ppm was loaded successfully!
Negative operation is done!
negative.ppm was saved successfully.
negative.jpg was stored for viewing.
Negative tested!

HSSOE.ppm was loaded successfully!
Color filter operation is done!
colorfilter.ppm was saved successfully.
colorfilter.jpg was stored for viewing.
Color Filter tested!

HSSOE.ppm was loaded successfully!
Edge operation is done!
edge.ppm was saved successfully.
edge.jpg was stored for viewing.
Edge tested!

HSSOE.ppm was loaded successfully!
Shuffle operation is done!
shuffle.ppm was saved successfully.
shuffle.jpg was stored for viewing.
Shuffle tested!

HSSOE.ppm was loaded successfully!
VFlip operation is done!
vflip.ppm was saved successfully.
vflip.jpg was stored for viewing.
VFlip tested!

HSSOE.ppm was loaded successfully!
vmirror.ppm was saved successfully.
vmirror.jpg was stored for viewing.
VMirror opeartion is done!
vmirror.ppm was saved successfully.
vmirror.jpg was stored for viewing.
VMirror tested!

HSSOE.ppm was loaded successfully!
Border operation is done!
border.ppm was saved successfully.
border.jpg was stored for viewing.
AddBorder tested!

--------------------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG formet
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image 
 6: Sketch the edge of an image 
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Adder Border to an iamge
11: Test all functions
12: Exit
Please make your choice: 12
]0;yukih1@zuma:hw2[yukih1@zuma hw2]$ exit
exit

Script done on Tue 24 Oct 2017 11:22:19 AM PDT
